import { useCallback, useEffect, useState } from "react";

import { ApiError, documentsApi } from "../lib/api";
import { useAuth } from "../context/AuthContext";

function formatDate(value) { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "No expiry"; }
function formatBytes(bytes) { if (!bytes) return "0 B"; const units = ["B", "KB", "MB", "GB"]; const index = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1); return `${(bytes / 1024 ** index).toFixed(index ? 1 : 0)} ${units[index]}`; }

export default function SharedWithMePage() {
  const { token } = useAuth();
  const [shares, setShares] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [downloading, setDownloading] = useState(null);
  const load = useCallback(async () => { setError(""); try { setShares(await documentsApi.listShared(token)); } catch (requestError) { setError(requestError instanceof ApiError ? requestError.message : "Unable to load shared documents."); } finally { setLoading(false); } }, [token]);
  useEffect(() => { load(); }, [load]);
  const download = async (shared) => { setDownloading(shared.document.id); try { const { blob, filename } = await documentsApi.download(token, shared.document.id); const url = URL.createObjectURL(blob); const anchor = window.document.createElement("a"); anchor.href = url; anchor.download = filename || shared.document.filename; anchor.click(); URL.revokeObjectURL(url); } catch (requestError) { setError(requestError instanceof ApiError ? requestError.message : "Unable to download the document."); } finally { setDownloading(null); } };
  return <div className="mx-auto max-w-6xl"><p className="text-sm font-semibold text-blue-600">Collaboration</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">Shared with me</h1><p className="mt-2 text-slate-600">Documents currently shared with your account.</p>{error && <div className="mt-6 flex justify-between rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700"><span>{error}</span><button onClick={load} className="font-semibold">Retry</button></div>}<section className="mt-7">{loading ? <div className="grid min-h-60 place-items-center rounded-2xl border border-slate-200 bg-white text-sm text-slate-500">Loading shared documents…</div> : shares.length ? <div className="grid gap-4 md:grid-cols-2">{shares.map((shared) => <article key={shared.document.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold text-slate-900" title={shared.document.filename}>{shared.document.filename}</p><p className="mt-1 text-sm text-slate-500">Owner: User #{shared.document.owner_id}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${shared.permission === "DOWNLOAD" ? "bg-blue-50 text-blue-700" : "bg-slate-100 text-slate-700"}`}>{shared.permission}</span></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-slate-400">Type</dt><dd className="mt-1 font-medium text-slate-700">{shared.document.document_type}</dd></div><div><dt className="text-slate-400">Size</dt><dd className="mt-1 font-medium text-slate-700">{formatBytes(shared.document.file_size)}</dd></div><div className="col-span-2"><dt className="text-slate-400">Access expires</dt><dd className="mt-1 font-medium text-slate-700">{formatDate(shared.expires_at)}</dd></div></dl>{shared.permission === "DOWNLOAD" && <button disabled={downloading === shared.document.id} onClick={() => download(shared)} className="mt-5 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white hover:bg-slate-800 disabled:opacity-60">{downloading === shared.document.id ? "Downloading…" : "Download PDF"}</button>}</article>)}</div> : <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><h2 className="text-lg font-semibold text-slate-900">Nothing shared with you yet</h2><p className="mt-2 text-sm text-slate-500">When someone grants you access, their active documents will appear here.</p></div>}</section></div>;
}
